title: Logeman Lab
description: Studying the neural mechanisms that control social behavior.
url: "https://blogeman.github.io"
baseurl: "/lab_website"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

